name: findit
description: "This ia a perfect demonstration for flutter complex implementation knowledge"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/brands/
    - assets/images/
    - assets/logos/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 300
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600